### ISSUE TITLE
Sweep system for Lynda.com links and fix or replace

### ISSUE THREAD

**Issue by andrewbattista** [andrewbattista/lgwg#18]
Lynda.com switched over to LinkedIn Learning. The cleanup and information control surrounding this is a bit more challenging and requires a strategy to make sure that all old Lynda.com content is switched over

**Comment by Jem706** [comment]
Project is underway, nearing completion.

I have changed links, some text (any mention of lynda or lynda.com to LinkedIn Learning), and also replaced 'link assets' with the 'A-Z Database Asset' for LinkedIn Learning.

I've kept notes on an auditing log (a google sheet) called "Libguide Auditing!"

Lynda information is on 'Lynda' sheet:

https://docs.google.com/spreadsheets/d/1zRY5RR51BTQwIsx1z8ZQykca_MyhWx-XARH1akZKF44/edit?usp=sharing

**Comment by Jem706** [comment]
All instances of "lynda" or "lynda.com" are scrubbed except for the following instances:

- A Lynda playlist that does not currently have a corresponding LinkedIn Learning version
- When Lynda is used to describe LinkedIn Learning's previous name (for example "LinkedIn Learning (previously lynda.com)"
- A Lynda video or course that was retired ("We’re sorry! The course has been retired.")

For each of these instances, the owner has been identified and their email collected. I will author a canned email to be sent to each owner that describes the situation and offers my help for fixing the error.

**Comment by andrewbattista** [comment]
Thanks, James!
