### ISSUE TITLE
Fix Primo widget on our ebooks page

### ISSUE THREAD

**Issue by andrewbattista** [andrewbattista/lgwg#45]
The widget to search BobCat seems to have degraded with recent changes. See https://guides.nyu.edu/ebooks

**Comment by AmericanIris** [comment]
@andrewbattista this would actually fall into web services who manages the search widgets in the locker box. @etgrieco would be the tech lead on resolving the issue.

**Comment by etgrieco** [comment]
@andrewbattista taking a look at this now, thanks for keeping up with this. We deprecated the `keywordsearch` API a while ago, so I'll create an ebook search widget in the lockerbox that is accessible and works.

**Comment by etgrieco** [comment]
Working draft of Ebooks search, consistent with our other single-use search widgets, available at `BoxID: 21988659`. 

Preview at: https://guides.nyu.edu/c.php?g=276565&p=1848163

Awaiting review from @AmericanIris or @lisagayhart

**Comment by andrewbattista** [comment]
Thank you @etgrieco - I pasted in the URL into the existing widget. Open to coordinating on a more organized and sophisticated way of provisioning widgets than the LockerBox
